// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArticleImageProgress(arg1) {
  return window['go']['api']['ATController']['GetArticleImageProgress'](arg1);
}

export function GetLogHistory() {
  return window['go']['api']['ATController']['GetLogHistory']();
}

export function InitConfig() {
  return window['go']['api']['ATController']['InitConfig']();
}

export function LoadArticles(arg1, arg2) {
  return window['go']['api']['ATController']['LoadArticles'](arg1, arg2);
}

export function OpenDir(arg1) {
  return window['go']['api']['ATController']['OpenDir'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['api']['ATController']['OpenFile'](arg1);
}

export function Print(arg1, arg2, arg3) {
  return window['go']['api']['ATController']['Print'](arg1, arg2, arg3);
}

export function PushLog(arg1) {
  return window['go']['api']['ATController']['PushLog'](arg1);
}

export function Run() {
  return window['go']['api']['ATController']['Run']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['api']['ATController']['SaveFile'](arg1, arg2, arg3);
}

export function SetDBController(arg1) {
  return window['go']['api']['ATController']['SetDBController'](arg1);
}

export function SetProxyURL(arg1) {
  return window['go']['api']['ATController']['SetProxyURL'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['ATController']['Startup'](arg1);
}

export function UpdateArticleStatus(arg1, arg2) {
  return window['go']['api']['ATController']['UpdateArticleStatus'](arg1, arg2);
}
