// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {artlog} from '../models';
import {api} from '../models';
import {context} from '../models';
import {models} from '../models';

export function GenArticleDetail(arg1:number):Promise<void>;

export function GetLogHistory():Promise<utils.ResponseJSON>;

export function GetRecordID():Promise<utils.ResponseJSON>;

export function InitConfig():Promise<void>;

export function LoadArticles(arg1:string,arg2:string):Promise<utils.ResponseJSON>;

export function OpenDir(arg1:string):Promise<utils.ResponseJSON>;

export function OpenFile(arg1:string):Promise<utils.ResponseJSON>;

export function Print(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PushLog(arg1:artlog.LoggerResult):Promise<void>;

export function Run():Promise<utils.ResponseJSON>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<utils.ResponseJSON>;

export function SetDBController(arg1:api.DBController):Promise<void>;

export function SetProxyURL(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateArticleDetail(arg1:number,arg2:models.Platform):Promise<void>;

export function UpdateInterfaceRecord(arg1:models.InterfaceRecord,arg2:utils.NetWorkController,arg3:models.Platform,arg4:number,arg5:models.Interface):Promise<models.InterfaceRecord>;
