// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoMigrate() {
  return window['go']['api']['DBController']['AutoMigrate']();
}

export function CheckConnect() {
  return window['go']['api']['DBController']['CheckConnect']();
}

export function Connect(arg1) {
  return window['go']['api']['DBController']['Connect'](arg1);
}

export function CreateInterface(arg1) {
  return window['go']['api']['DBController']['CreateInterface'](arg1);
}

export function CreateOrUpdateInterfaceRecord(arg1) {
  return window['go']['api']['DBController']['CreateOrUpdateInterfaceRecord'](arg1);
}

export function CreatePlatform(arg1) {
  return window['go']['api']['DBController']['CreatePlatform'](arg1);
}

export function DeleteInterfaces(arg1) {
  return window['go']['api']['DBController']['DeleteInterfaces'](arg1);
}

export function DeletePlatforms(arg1) {
  return window['go']['api']['DBController']['DeletePlatforms'](arg1);
}

export function ExportPlatform(arg1, arg2) {
  return window['go']['api']['DBController']['ExportPlatform'](arg1, arg2);
}

export function GetConfigDir() {
  return window['go']['api']['DBController']['GetConfigDir']();
}

export function GetConfigFilePath() {
  return window['go']['api']['DBController']['GetConfigFilePath']();
}

export function GetInterface(arg1) {
  return window['go']['api']['DBController']['GetInterface'](arg1);
}

export function GetInterfaceRecords(arg1) {
  return window['go']['api']['DBController']['GetInterfaceRecords'](arg1);
}

export function GetPlatform(arg1) {
  return window['go']['api']['DBController']['GetPlatform'](arg1);
}

export function GetPlatforms(arg1) {
  return window['go']['api']['DBController']['GetPlatforms'](arg1);
}

export function ImportPlatform(arg1) {
  return window['go']['api']['DBController']['ImportPlatform'](arg1);
}

export function LoadJSONFile(arg1) {
  return window['go']['api']['DBController']['LoadJSONFile'](arg1);
}

export function SaveJSONFile(arg1, arg2) {
  return window['go']['api']['DBController']['SaveJSONFile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['api']['DBController']['Startup'](arg1);
}

export function UpdateInterface(arg1) {
  return window['go']['api']['DBController']['UpdateInterface'](arg1);
}

export function UpdatePlatform(arg1) {
  return window['go']['api']['DBController']['UpdatePlatform'](arg1);
}
